//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.esri.webops.feduc2013;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ListView;
import android.widget.TextView;
import com.esri.webops.feduc2013.R.id;
import com.esri.webops.feduc2013.R.layout;

public final class ExhibitsSponsor_
    extends ExhibitsSponsor
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.exhibits_sponsor);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        all_txvw = ((TextView) findViewById(id.all_txvw));
        empty_txvw = ((TextView) findViewById(id.empty_txvw));
        sponsorList = ((ListView) findViewById(id.sponsorList));
        sponsor_txvw = ((TextView) findViewById(id.sponsor_txvw));
        hours_txvw = ((TextView) findViewById(id.hours_txvw));
        {
            View view = findViewById(id.refresh_btn);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ExhibitsSponsor_.this.refresh_btn();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.hours_txvw);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ExhibitsSponsor_.this.hours_txvw();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.all_txvw);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ExhibitsSponsor_.this.all_txvw();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.map_btn);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ExhibitsSponsor_.this.map_btn();
                    }

                }
                );
            }
        }
        loadView();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static ExhibitsSponsor_.IntentBuilder_ intent(Context context) {
        return new ExhibitsSponsor_.IntentBuilder_(context);
    }

    @Override
    public void updateUI() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    ExhibitsSponsor_.super.updateUI();
                } catch (RuntimeException e) {
                    Log.e("ExhibitsSponsor_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ExhibitsSponsor_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ExhibitsSponsor_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
